const Constants = {
	// Advisories
	UPDATED_ADVISORIES: "UPDATED_ADVISORIES",
	FETCH_ADVISORIES: "FETCH_ADVISORIES",
	FETCH_ADVISORIES_ERROR: "FETCH_ADVISORIES_ERROR",
	RECEIVED_ADVISORIES: "RECEIVED_ADVISORIES",

	// Trip information from an origin to a destination.
	UPDATED_TRIPS: "UPDATED_TRIPS",
	FETCH_TRIPS: "FETCH_TRIPS",
	FETCH_TRIPS_ERROR: "FETCH_TRIPS_ERROR",
	RECEIVED_TRIPS: "RECEIVED_TRIPS",
	CHANGE_ORIGIN: "CHANGE_ORIGIN",
	CHANGE_DESTINATION: "CHANGE_DESTINATION"
};

export default Constants;
